cluster.name: my-cluster
node.name: node-1
network.host: 0.0.0.0
bootstrap.memory_lock: true
cluster.initial_master_nodes: ["node-1"]

# Security and TLS Settings
xpack.security.enabled: true

# HTTP SSL Configuration
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: certs/elasticsearch/elasticsearch.key
xpack.security.http.ssl.certificate: certs/elasticsearch/elasticsearch.crt
xpack.security.http.ssl.certificate_authorities: ["certs/ca/ca.crt"]

# Transport SSL Configuration
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.key: certs/elasticsearch/elasticsearch.key
xpack.security.transport.ssl.certificate: certs/elasticsearch/elasticsearch.crt
xpack.security.transport.ssl.certificate_authorities: ["certs/ca/ca.crt"]
