server.host: "0.0.0.0"
server.ssl.enabled: true
monitoring.ui.container.elasticsearch.enabled: true
server.ssl.certificate: config/certs/ca/ca.crt
server.ssl.key: config/certs/ca/ca.key
elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/certs/ca/ca.crt"]
elasticsearch.hosts: ["https://elasticsearch:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "${KIBANA_PASSWORD}"
